charts,images: Remove separate metering-presto image
Move all configuration files from Presto image into Presto chart
avoiding the need for the metering-presto image

This also required
https://github.com/operator-framework/presto/commit/ae85f2d7cd4e2fac275d64664e8e5a29a9e7477a
to the Presto base image. That commit which sets the user to a non-root
UID (1003) by default, and ensures /etc/passwd is writable by the
default user, or a process with an EGID of 0. This is required because
we set runAsNonRoot in the Presto deployment. /etc/passwd must be
writable to GID 0 for the entrypoint to add the current user's to
/etc/passwd when the UID changes (like in Openshift).

diff --git a/charts/presto/templates/presto-common-config.yaml b/charts/presto/templates/presto-common-config.yaml
--- a/charts/presto/templates/presto-common-config.yaml
+++ b/charts/presto/templates/presto-common-config.yaml
@@ -5,7 +5,56 @@ metadata:
 {{- block "extraMetadata" . }}
 {{- end }}
 data:
-  environment: {{ .Values.spec.presto.con***REMOVED***g.environment | quote }}
-  discovery-uri: {{ .Values.spec.presto.con***REMOVED***g.discoveryURI | quote }}
-  hive-metastore-uri: {{ .Values.spec.presto.con***REMOVED***g.hiveMetastoreURI }}
+  entrypoint.sh: |
+    #!/bin/bash
 
+    max_memory() {
+        local memory_limit=$1
+        local ratio=${JAVA_MAX_MEM_RATIO:-50}
+        echo "${memory_limit} ${ratio} 1048576" | awk '{printf "%d\n" , ($1*$2)/(100*$3) + 0.5}'
+    }
+
+    # Check for container memory limits/request and use it to set JVM Heap size.
+    # Defaults to 50% of the limit/request value.
+    if [ -n "$MY_MEM_LIMIT" ]; then
+        export MAX_HEAPSIZE="$( max_memory $MY_MEM_LIMIT )"
+    elif [ -n "$MY_MEM_REQUEST" ]; then
+        export MAX_HEAPSIZE="$( max_memory $MY_MEM_REQUEST )"
+    ***REMOVED***
+
+    if [ -z "$MAX_HEAPSIZE" ]; then
+        echo "Unable to automatically set Presto JVM Max Heap Size based on pod request/limits"
+        export MAX_HEAPSIZE=1024
+        echo "Setting Presto JVM Max Heap Size to ${MAX_HEAPSIZE}M"
+    ***REMOVED***
+        echo "Setting Presto JVM Max Heap Size to ${MAX_HEAPSIZE}M"
+    ***REMOVED***
+
+    # add heapsize to jvm con***REMOVED***g if not already
+    JVM_CONFIG="${PRESTO_HOME}/etc/jvm.con***REMOVED***g"
+    if ! grep -q -F 'Xmx' "$JVM_CONFIG"; then
+      FLAG="-Xmx${MAX_HEAPSIZE}M"
+      echo "Adding $FLAG to $JVM_CONFIG"
+      echo "$FLAG" >> "$JVM_CONFIG"
+    ***REMOVED***
+
+    # add node id to node con***REMOVED***g
+    NODE_CONFIG="${PRESTO_HOME}/etc/node.properties"
+    if ! grep -q -F 'node.id' "$NODE_CONFIG"; then
+      NODE_ID="node.id=$MY_NODE_ID"
+      echo "Adding $NODE_ID to $NODE_CONFIG"
+      echo "$NODE_ID" >> "$NODE_CONFIG"
+    ***REMOVED***
+
+    # add UID to /etc/passwd if missing
+    if ! whoami &> /dev/null; then
+        if [ -w /etc/passwd ]; then
+            echo "Adding user ${USER_NAME:-presto} with current UID $(id -u) to /etc/passwd"
+            # Remove existing entry with user ***REMOVED***rst
+            sed -i "/${USER_NAME:-presto}:x/d" /etc/passwd
+            # add our user with our current user ID into passwd
+            echo "${USER_NAME:-presto}:x:$(id -u):0:${USER_NAME:-presto} user:${HOME}:/sbin/nologin" >> /etc/passwd
+        ***REMOVED***
+    ***REMOVED***
+
+    exec "$@"
